name: Docker Build and Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-snake-game:latest .

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-snake-game:latest
