name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t yourdockerhubusername/my-snake-game:latest .
        docker push yourdockerhubusername/my-snake-game:latest

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        # Write the private key to a file
        echo "$PRIVATE_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem

        # Connect to EC2 and deploy the Docker container
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem $USER@$HOST << 'EOF'
        docker pull yourdockerhubusername/my-snake-game:latest
        docker stop my-snake-game || true
        docker rm my-snake-game || true
        docker run -d -p 80:80 --name my-snake-game yourdockerhubusername/my-snake-game:latest
        EOF

        # Clean up the key file
        rm ec2-key.pem
