name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         
      - name: Build docker image
        run: docker build -t aziz529/snack-game/Test-game .
      - name: Publish image to docker hub
        run: docker push aziz529/snack-game/Test-game:latest
        
  deploy:
    needs: build
    runs-on: [ip-172-31-32-202]
    steps:
      - name: Pull image from docker hub
        run: docker pull aziz529/snack-game/Test-game:latest
      - name: Delete old container
        run: docker rm -f Test-game-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container aziz529/snack-game/Test-game
