name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Your AWS region

      - name: Get ECR login password
        id: ecr-login
        run: echo "::set-output name=password::$(aws ecr get-login-password --region ap-south-1)"

      - name: Login to Amazon ECR
        uses: docker/login-action@v2
        with:
          username: AWS
          password: ${{ steps.ecr-login.outputs.password }}
          registry: your-account-id.dkr.ecr.ap-south-1.amazonaws.com  # Update with your ECR registry URL

      - name: Build Docker image
        run: docker build -t your-account-id.dkr.ecr.ap-south-1.amazonaws.com/testgame:latest .

      - name: Push image to Amazon ECR
        run: docker push your-account-id.dkr.ecr.ap-south-1.amazonaws.com/testgame:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Your AWS region

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ExpresstestNew --service service --force-new-deployment
