name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Get ECR login password
        id: ecr-login
        run: echo "ECR_PASSWORD=$(aws ecr get-login-password --region ap-south-1)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: docker/login-action@v2
        with:
          username: AWS
          password: ${{ env.ECR_PASSWORD }}
          registry: 025066249719.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t 025066249719.dkr.ecr.ap-south-1.amazonaws.com/aziz529/snack-game:latest .

      - name: Push image to Amazon ECR
        run: docker push 025066249719.dkr.ecr.ap-south-1.amazonaws.com/aziz529/snack-game:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ExpresstestNew --service service --force-new-deployment
