name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the Docker image to Amazon ECR
        run: |
          docker build -t aziz529/snack-game .
          docker tag aziz529/snack-game:latest 025066249719.dkr.ecr.ap-south-1.amazonaws.com/aziz529/snack-game:latest
          docker push 025066249719.dkr.ecr.ap-south-1.amazonaws.com/aziz529/snack-game:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: config/ecs-task-definition.json
          service: my-ecs-service
          cluster: Expresstest  # Use the correct cluster name
          wait-for-service-stability: true
