name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Login to Amazon ECR
        uses: docker/login-action@v2
        with:
          username: AWS
          password: ${{ secrets.AWS_ECR_PASSWORD }}
          registry: your-account-id.dkr.ecr.your-region.amazonaws.com

      - name: Build Docker image
        run: docker build -t your-account-id.dkr.ecr.your-region.amazonaws.com/testgame:latest .

      - name: Push image to Amazon ECR
        run: docker push your-account-id.dkr.ecr.your-region.amazonaws.com/testgame:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ExpresstestNew --service service --force-new-deployment
